version: '3'
services:
  kibana-prd:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5601:5601

  kibana-hml:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5602:5601
