version: '3'
services:
  kibana-prd:
    image: docker.elastic.co/kibana/kibana:7.7.1-local
    ports:
      - 5601:5601
    volumes:
      - ./config/local/prd:/usr/share/kibana/config/:ro

  kibana-hml:
    image: docker.elastic.co/kibana/kibana:7.7.1-local
    ports:
      - 5602:5601
    volumes:
      - ./config/local/hml:/usr/share/kibana/config/:ro
