version: '3'
services:
  kibana-prd:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5601:5601
    volumes:
      - ./PRDConfig:/usr/share/kibana/config/:ro

  kibana-hml:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5602:5601
    volumes:
      - ./HMLConfig:/usr/share/kibana/config/:ro
