version: '3'
services:
  kibana-qa:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - 5602:5601
    volumes:
      - ./config:/usr/share/kibana/config/:ro
    networks:
      - elastic

networks:
  elastic:
    driver: bridge